CREATE TABLE IF NOT EXISTS cows (
  id VARCHAR(24) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  breed VARCHAR(100) NOT NULL,
  sex VARCHAR(20) NOT NULL,
  birth_date DATE NULL,
  stage VARCHAR(32) NOT NULL DEFAULT 'ให้นม',
  avg_yield DECIMAL(8, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS milk_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cow_id VARCHAR(24) NULL,
  record_date DATE NOT NULL,
  milking_round VARCHAR(16) NOT NULL,
  amount DECIMAL(8, 2) NOT NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_milk_cow FOREIGN KEY (cow_id) REFERENCES cows(id) ON UPDATE CASCADE ON DELETE SET NULL,
  INDEX idx_milk_date_round (record_date, milking_round),
  INDEX idx_milk_cow_date (cow_id, record_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS care_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cow_id VARCHAR(24) NOT NULL,
  category VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_date DATE NOT NULL,
  note TEXT NULL,
  next_date DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_event_cow FOREIGN KEY (cow_id) REFERENCES cows(id) ON UPDATE CASCADE ON DELETE CASCADE,
  INDEX idx_event_date (event_date),
  INDEX idx_event_cow_date (cow_id, event_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS farm_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  role VARCHAR(32) NOT NULL DEFAULT 'ผู้ปฏิบัติงาน',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS milk_quality_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  record_date DATE NOT NULL,
  scc INT UNSIGNED NULL,
  fat_pct DECIMAL(5, 2) NULL,
  snf_pct DECIMAL(5, 2) NULL,
  mb_test VARCHAR(32) NULL,
  income DECIMAL(12, 2) NULL,
  source_file VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_quality_date (record_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS farm_settings (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  farm_name VARCHAR(100) NULL,
  owner_name VARCHAR(100) NOT NULL,
  farm_code VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_preferences (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  dry_off TINYINT(1) NOT NULL DEFAULT 1,
  health_care TINYINT(1) NOT NULL DEFAULT 1,
  breeding TINYINT(1) NOT NULL DEFAULT 1,
  milk_quality TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;